### ISSUE TITLE
[Bug] (Gtk-WARNING cannot open display)

### ISSUE THREAD

**Issue by bugmaschine** [e6Hub/app#10]
**What is the bug?**
When i try to run the dev build i tells me (electron:21925): Gtk-WARNING **: 20:36:20.409: cannot open display: 

**Steps to reproduce that**
1.Run Dev on Arch Linux
2. Wait
3. ???
4. Profit

**Machine info**
* OS Manjaro

**Comment by xaeky** [comment]
Usually this error is thrown when you're trying to open an Electron app with administrator privileges (sudo). Would be good if you can attach a screenshot of the error.

**Comment by bugmaschine** [comment]
Thanks i somehow forgot that i shouldn't run stuff with sudo
