### ISSUE TITLE
[Bug] Can't download posts

### ISSUE THREAD

**Issue by aexhell** [e6Hub/app#11]
**What is the bug?**
I was trying to download some posts, but for some reason they are not downloading. I can't check Dev Tools as much as I try.

**Steps to reproduce that**
1. Search a post.
2. Click the post's view.
3. Click the "Download" button.
4. If you go to "Downloads", the post will not download and it will get stuck at 0%.

**Machine info**
* OS: Windows 8.1 on 64 bits.
* App version: 3.7.0.
![Screenshot_1](https://user-images.githubusercontent.com/47114174/106368952-dc9f6f80-634d-11eb-9c96-509849d15f4a.png)

**Comment by xaeky** [comment]
Issue was identified, `pluginman.js` can throw an error while getting all the plugins from the plugins folder. That means that majority of features of the apps stop working if a module (in this case, pluginman) throw an error.
